spring.application.name=md4-ss9-exe01

#C?u hình DB
spring.datasource.url=jdbc:mysql://localhost:3306/ss9_exe01
spring.datasource.username=root
spring.datasource.password=Nguyenthuy92@

spring.jpa.hibernate.ddl-auto=update
